### ISSUE TITLE
Has compatibility problems when introduced the config sink

### ISSUE THREAD

**Issue by atlas-comstock** [talariadb/talaria#103]
https://github.com/talariadb/talaria/pull/86/files

This MR introduced `sink` configs, which means to abstract writers, however it does not compatable with old config files.

**Comment by atlas-comstock** [comment]
I prefer that we do not introduce any compatibility problems when possible. cc @kelindar @tardunge

**Comment by tardunge** [comment]
@atlas-comstock I could not get the issue you are facing. Just incase if i understood correctly..
The MR[pull-86] has breaking changes. One needs to update the config file and configure `sinks` as a list instead
of a map.
For Sinks being a map, we cannot use sinks from same provider, as the last read key-value pair will override the previous one. This is important for fanout streams/sinks with different filters and different destinations belonging to a single data-storage provider.
ex:
```
sinks:
   \- bigquery:
         # sink conf for table-1
         - filter: filter based on some constraint
         
   \- bigquery:
          # sink conf for table-2
         - filter: filter based on a different constraint
```
Any thoughts on achieving this behaviour without compromising on backward compatibility for configs?
